### ISSUE TITLE
What is it mybot.js?

### ISSUE THREAD

**Issue by vmoshikov** [bostrot/telegram-support-bot#1]
Hi. I need help.
I run "1 npm install telegraf --save
2 git clone https://github.com/bostrot/telegram-support-bot.git
3 cd telegram-support-bot" it's good, but "sudo bash setup" ask me "Enter your bot location". I did't have it. What shol i do? I need your paid support this run project

**Comment by bostrot** [comment]
This bot has two main features.
First is the **support** one - You can create a support chat with it.
Second is the bot **controller** - With this you can control your main bot ( if you have one ). Start, restart, stop, ... it.

So when you only need this bot for the support feature, create a file `/etc/systemd/system/support.service` with this content:

    [Unit]
    Description=support

    [Service]
    ExecStart=/usr/bin/node path/to/telegram-support-bot/setup/support.js
    [Install]
    WantedBy=multi-user.target

then enable it to autostart with `systemctl enable support`

**Comment by vmoshikov** [comment]
Eric, I trying to run project in cloud9 (c9.io)
I get error in 187 Line
`Debugger listening on [::]:15454
/home/ubuntu/workspace/telegram-support-bot/bin/support.js:187
  })
   ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Timeout.Module.runMain [as _onTimeout] (module.js:604:10)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)`
I remove ' ) ' adn error move to 311 line BUT file have all 310 line... How?
`Debugger listening on [::]:15454
/home/ubuntu/workspace/telegram-support-bot/bin/support.js:311
});
  ^

SyntaxError: Unexpected end of input
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Timeout.Module.runMain [as _onTimeout] (module.js:604:10)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
`

**Comment by bostrot** [comment]
@vmoshikov thanks for reporting that. I fixed this formatting issue and uploaded the fix.

**Comment by vmoshikov** [comment]
@bostrot Thanks you for the development of the library.
I undestand how this start. Where to get structure BD

**Comment by vmoshikov** [comment]
I started it!
What to do next? ))

**Comment by bostrot** [comment]
It's pretty straight forward in the Readme file. Configure it.

**Comment by vmoshikov** [comment]
I configure it.
BotToken get from BotFather
staff_chat get from https://api.telegram.org/bot<YourBOTToken>/getUpdates it have format (-12345678)
owner_id get from @getidsbot

All right?

**Comment by bostrot** [comment]
Format of both IDs are 12345678 but yes that's it.

**Comment by vmoshikov** [comment]
@bostrot all right, but Bot Telegram has not changed, he is still silent

**Comment by bostrot** [comment]
I assume you configured your database correctly?

```
/* edit below */
const bot = new Telegraf('BOT_TOKEN_SUPPORT_BOT') // support bot token
var staff_chat = 'SUPPORT_STAFF_GROUP_ID' // telegram staff group chat id
var owner_id = 'OWNER_ID' // telgram owner id
var supported_bot = 'service_name' // service name of the supported bot
var startCommandText = 'Welcome in our support chat! Ask your question here.'
var faqCommandText = 'Check out our FAQ here: https://bitgram.pro/index.php/bitgram-faq'
var con = mysql.createConnection({ // only needed if you want to get user info from a mysql database with /id command
  host: 'HOST',
  user: 'USR',
  password: 'PWD',
  database: 'DB'
})
/* edit end */
```

**Comment by vmoshikov** [comment]
I have configured database.
I think... How does support.js communicate from telegraf?
I have it:
<img width="287" alt="2017-11-19 23 34 58" src="https://user-images.githubusercontent.com/33805085/32995210-508c0396-cd82-11e7-8276-26049241d34d.png">

**Comment by bostrot** [comment]
Contact my over Telegram @Bostrot I will try to help you

**Comment by bostrot** [comment]
Try https://github.com/bostrot/telegram-support-bot/commit/2f82630c5a5fa399ccdbfdc4293caca252df667a and reply if it works for you.
