### ISSUE TITLE
Sending message from WEB isn't working

### ISSUE THREAD

**Issue by gituser** [bostrot/telegram-support-bot#141]
**Describe the bug**
When trying to send a message from WEB bot crashes with message (code was check from latest `master`, also tried latest `v4.1.1` tag):

```
Web message
=== UNHANDLED ERROR ===
Mon Apr 03 2023 13:56:15: Error:  TypeError: Cannot read property 'toString' of undefined
    at Object.msg (/home/www/telegram-support/src/middleware.ts:67:10)
    at /home/www/telegram-support/src/users.ts:126:22
    at Object.getOpen (/home/www/telegram-support/src/db.ts:42:3)
    at Object.chat (/home/www/telegram-support/src/users.ts:91:8)
    at /home/www/telegram-support/src/text.ts:51:17
    at Object.getOpen (/home/www/telegram-support/src/db.ts:42:3)
    at ticketHandler (/home/www/telegram-support/src/text.ts:44:8)
    at Socket.<anonymous> (/home/www/telegram-support/src/addons/web.ts:56:26)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
```

**To Reproduce**
1. set in `config/config.yaml`:
```
web_server: true # Enable/disable web server
web_server_port: 8080 # Port for web server
```
2. Visit http://localhost:8080
3. Enter some message inside chat widget

**Versions**

```
# node --version
v14.21.1
```

Also [demo version](https://erictrenkel.com/chat.html) specified here - https://github.com/bostrot/telegram-support-bot/wiki/Addons#web-chat seems to be not working.

**Comment by JayDi85** [comment]
Fix for a web chat can be found in PR: #157
