### ISSUE TITLE
Symbols not escaped (Markdown/MarkdownV2)

### ISSUE THREAD

**Issue by Geparder** [bostrot/telegram-support-bot#149]
"Thu May 25 2023 11:16:53 GMT+0000 (Coordinated Universal Time): GrammyError: Call to 'sendMessage' failed! (400: Bad Request: can't parse entities: Character '(' is reserved and must be escaped with the preceding '\\')\n" +
2023-05-25T11:16:53.434547877Z   '    at toGrammyError (/bot/node_modules/grammy/out/core/error.js:35:12)\n' +
2023-05-25T11:16:53.434553744Z   '    at ApiClient.callApi (/bot/node_modules/grammy/out/core/client.js:86:48)'

**Comment by gituser** [comment]
ping @bostrot

**Comment by gituser** [comment]
There is an issue with escaping, e.g. if you try to send this text with `MarkdownV2` syntax it will fail:

```
Test (
'elem1' => 'test123',
'elem2' => 'test345',
'elem3' => 'test444',
)
```
This is because of the escape rules defined here for urls - https://github.com/bostrot/telegram-support-bot/blob/master/src/middleware.ts#L41

The error in the log will look like this:
```
GrammyError: Call to 'sendMessage' failed! (400: Bad Request: can't parse entities: Character '=' is reserved and must be escaped with the preceding '\')
```
Easiest fix is to comment this block of code, but then again for URL markdown won't work.

Also noticed that `MarkdownV2` strips all tags like code tags ``` and send to the user as a plaintext message.

Maybe you could take a look at this issue @bostrot.

Thanks.

**Comment by bostrot** [comment]
v5.0.0 should make this a little better.

Closing as this is pretty old. If you are still encountering this issue feel free to reopen.
