### ISSUE TITLE
TypeError: Cannot open database because the directory does not exist at new Database

### ISSUE THREAD

**Issue by pilotseye** [bostrot/telegram-support-bot#18]
**Describe the bug**
Support.db cannot be found when starting support.js from root directory

/root/telegram-support-bot/node_modules/better-sqlite3/lib/database.js:31
                throw new TypeError('Cannot open database because the directory                                         does not exist');
                ^

TypeError: Cannot open database because the directory does not exist
    at new Database (/root/telegram-support-bot/node_modules/better-sqlite3/lib/                                        database.js:31:9)
    at Object.<anonymous> (/root/telegram-support-bot/bin/dbhandler.js:2:12)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/telegram-support-bot/bin/ticket_handler.js:3:17                                        )

**To Reproduce**
At root directory start support.js, e.g.  "node /root/telegram-support-bot/bin/support.js"

**Expected behavior**
support.db should not only be accessible from inside /telegram-support-bot/
/bin/dbhandler.js may needs changes in regards to db path

**Desktop (please complete the following information):**
CentOS 7

**Comment by bostrot** [comment]
Added the relative path to the `dbhandler.js` so you should be able to start it from another path. (0159ad936ae1760419c1576ab5ef7cfae5393ecf)

**Comment by pilotseye** [comment]
Thanks, that fixed it, actually that was my workaround too, just not as beautiful as yours ;)
