### ISSUE TITLE
Any way to start the bot with a js file?

### ISSUE THREAD

**Issue by RFlintstone** [bostrot/telegram-support-bot#3]
Hi!

As the title says, is there any way to start the bot with a java script file?
I need one for my (new) host. I now use https://www.openode.io and can execute the setup file however the server wont start the bot (yet).

-Ruben

**Comment by bostrot** [comment]
Do you have an output after you ran it?

**Comment by RFlintstone** [comment]
When i used bash run (i cant use sudo) i get this:

```
$ bash setup
Bash script v1.0
Enter your bot location: /root
Enter your bot name: Flintcrafted Support
+ telegraf@3.17.3
added 6 packages in 3.802s
+ cron@1.3.0
added 3 packages in 3.302s
Creating /etc/systemd/system/support.service...
setup: line 8: /etc/systemd/system/support.service: No such file or directory
Creating /etc/systemd/system/Flintcrafted Support.service...
setup: line 10: /etc/systemd/system/${name}.service: ambiguous redirect
setup: line 11: systemctl: command not found
setup: line 12: systemctl: command not found

```

**Comment by bostrot** [comment]
This just means that your server doesn't have systemctl (This is to start it at the boot). You can use it without systemctl too. Just run it normally with Node. `node support.js`

**Comment by RFlintstone** [comment]
This is the output i get:

```
$ node support.js
module.js:540
    throw err;
    ^

Error: Cannot find module 'C:\Users\Bert F\telegram-support-bot\support.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

```
-Ruben
